{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "0030c43c",
   "metadata": {},
   "outputs": [],
   "source": [
    "from ipywidgets import interact, widgets\n",
    "from IPython.display import display, clear_output\n",
    "from boto3.dynamodb.conditions import Key, Attr\n",
    "from decimal import Decimal\n",
    "from functools import reduce\n",
    "from pymongo import MongoClient\n",
    "import pandas as pd\n",
    "import logging\n",
    "import re\n",
    "import boto3\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "6f0473ad",
   "metadata": {},
   "outputs": [],
   "source": [
    "client = MongoClient('localhost', 27017)\n",
    "db = client['351Project']\n",
    "collection = db['profiles']\n",
    "\n",
    "# establishes dynamo connection\n",
    "dynamodb = boto3.resource('dynamodb', region_name='us-west-1') # region name must match aws \n",
    "table = dynamodb.Table('video_game_profiles') "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "ba27c9c8",
   "metadata": {},
   "outputs": [],
   "source": [
    "def view_mongo():\n",
    "    \n",
    "    # to have labels in HTMl so it fits on the screen\n",
    "    def labeled_input(description, widget):\n",
    "        return widgets.VBox([widgets.Label(value=f\"{description}\"), widget])\n",
    "        \n",
    "    # widgets that will be displayed\n",
    "    view_choice = widgets.Dropdown(\n",
    "        options = ['All Profiles', 'Search Profile by Username'],\n",
    "    )\n",
    "    labeled_view_choice = labeled_input('View by: ', view_choice)\n",
    "\n",
    "    username = widgets.Text(\n",
    "        value = '',\n",
    "        placeholder = 'Enter username',\n",
    "        disabled = False,\n",
    "\n",
    "    )\n",
    "    labeled_username = labeled_input('Username: ', username)\n",
    "    labeled_username.layout.visibility = 'hidden'\n",
    "\n",
    "        \n",
    "    options = [ 'all', 'username', 'email', 'games_played', 'wins', 'losses',\n",
    "                  'kills', 'number_of_friends', 'favorite_weapon', 'money_spent', \n",
    "                  'favorite_character']\n",
    "    attributes = widgets.SelectMultiple(\n",
    "        options = options,\n",
    "        value = ['all'],\n",
    "        disabled = False\n",
    "    )\n",
    "    labeled_attributes = labeled_input(\"Attributes(hold command to select multiple): \", attributes)\n",
    "\n",
    "    search_button = widgets.Button(\n",
    "        description = 'View',\n",
    "        button_style = '',\n",
    "        tooltip = 'Click to search for a profile',\n",
    "        icon = 'view'\n",
    "    )\n",
    "    \n",
    "    clear_button = widgets.Button(\n",
    "        description = 'Clear', \n",
    "        button_style = '', \n",
    "        tooltip = 'Click to clear search', \n",
    "        icon = 'remove')\n",
    " \n",
    "    \n",
    "    output = widgets.Output()\n",
    "\n",
    "    # function so user can't select all along with the other options, only all, or only the other options\n",
    "    def select_all(change):\n",
    "        if 'all' in change['new']:\n",
    "            if len(change['new']) > 1:\n",
    "                if 'all' in change['old']:\n",
    "                    attributes.value = tuple(set(change['new']) - {'all'})\n",
    "                else:\n",
    "                    attributes.value = tuple(options[1:])\n",
    "            else:\n",
    "                attributes.value = ('all',)\n",
    "                \n",
    "    attributes.observe(select_all, 'value')\n",
    "\n",
    "    # function that allows user to view all profiles or view profile by username\n",
    "    # also allows user to select which attributes they would like to view or if they would like to view all of them\n",
    "    def valid_search(submission):\n",
    "        with output:\n",
    "            output.clear_output()\n",
    "            selected_attributes = attributes.value\n",
    "            if 'all' in selected_attributes:\n",
    "                selected_attributes = options[1:]\n",
    "\n",
    "            fields = {field: True for field in selected_attributes} \n",
    "            fields['_id'] = 0\n",
    "            if view_choice.value == 'All Profiles':\n",
    "                profiles = collection.find({}, fields)\n",
    "                for profile in profiles:\n",
    "                    display = ', '.join([f\"{key}: {value}\" for key, value in profile.items() if key != '_id'])\n",
    "                    print(display)\n",
    "            elif view_choice.value == \"Search Profile by Username\" and username.value:\n",
    "                profile = collection.find_one({\"username\": username.value}, fields)\n",
    "                if profile:\n",
    "                    out = ', '.join([f\"{key}: {value}\" for key, value in profile.items() if key != '_id'])\n",
    "                    print(out)\n",
    "                else:\n",
    "                    print(\"Username does not exist, Please Enter another one\")\n",
    "            else:\n",
    "                print(\"Invalid Choice or No username Entered\")\n",
    "\n",
    "    search_button.on_click(valid_search)\n",
    "    \n",
    "    # clear function to reset the searches when click is cleared\n",
    "    def clear(click):\n",
    "        with output:\n",
    "            clear_output()\n",
    "\n",
    "\n",
    "    clear_button.on_click(clear)\n",
    "\n",
    "    # function that only shows the username search widget when 'Search Profile by Username is selected'\n",
    "    def username_visibility(change):\n",
    "        if change['new'] == 'Search Profile by Username':\n",
    "            labeled_username.layout.visibility = 'visible'\n",
    "            username.layout.visibility = 'visible'\n",
    "        else:\n",
    "            labeled_username.layout.visibility = 'hidden'\n",
    "            username.layout.visibility = 'hidden'\n",
    "            username.value = ''\n",
    "    view_choice.observe(username_visibility, names = 'value')\n",
    "\n",
    "    # to display the GUI\n",
    "    buttons = widgets.HBox([search_button, clear_button])\n",
    "    layout = widgets.VBox([labeled_view_choice, labeled_username, labeled_attributes, buttons, output])\n",
    "    display(layout)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "3755e0cb",
   "metadata": {},
   "outputs": [],
   "source": [
    "def view_dynamo():\n",
    "\n",
    "    # Function to create labeled input widgets\n",
    "    def labeled_input(description, widget):\n",
    "        return widgets.VBox([widgets.Label(value=f\"{description}\"), widget])\n",
    "\n",
    "    # Widgets for user interface\n",
    "    view_choice = widgets.Dropdown(\n",
    "        options=['All Profiles', 'Search Profile by Username'],\n",
    "    )\n",
    "    labeled_view_choice = labeled_input('View by: ', view_choice)\n",
    "\n",
    "    username = widgets.Text(\n",
    "        value='',\n",
    "        placeholder='Enter username',\n",
    "        disabled=False,\n",
    "    )\n",
    "    labeled_username = labeled_input('Username: ', username)\n",
    "    labeled_username.layout.visibility = 'hidden'\n",
    "\n",
    "    options = ['all', 'username', 'email', 'games_played', 'wins', 'losses',\n",
    "               'kills', 'number_of_friends', 'favorite_weapon', 'money_spent',\n",
    "               'favorite_character']\n",
    "    attributes = widgets.SelectMultiple(\n",
    "        options=options,\n",
    "        value=['all'],\n",
    "        disabled=False\n",
    "    )\n",
    "    labeled_attributes = labeled_input(\"Attributes(hold command to select multiple): \", attributes)\n",
    "\n",
    "    search_button = widgets.Button(\n",
    "        description='View',\n",
    "        button_style='',\n",
    "        tooltip='Click to search for a profile',\n",
    "        icon='view'\n",
    "    )\n",
    "\n",
    "    clear_button = widgets.Button(\n",
    "        description='Clear',\n",
    "        button_style='',\n",
    "        tooltip='Click to clear search',\n",
    "        icon='remove')\n",
    "\n",
    "    output = widgets.Output()\n",
    "\n",
    "    # Function to handle attribute selection\n",
    "    def select_all(change):\n",
    "        if 'all' in change['new']:\n",
    "            if len(change['new']) > 1:\n",
    "                if 'all' in change['old']:\n",
    "                    attributes.value = tuple(set(change['new']) - {'all'})\n",
    "                else:\n",
    "                    attributes.value = tuple(options[1:])\n",
    "            else:\n",
    "                attributes.value = ('all',)\n",
    "\n",
    "    attributes.observe(select_all, 'value')\n",
    "\n",
    "    # function to perform valid search. if \"all\" is chosen, table scan is used and all results are returned. if \"search profile by\n",
    "    # username\" is chosen, table query is used instead\n",
    "    def valid_search(submission):\n",
    "        with output:\n",
    "            output.clear_output()\n",
    "            selected_attributes = attributes.value\n",
    "            if 'all' in selected_attributes:\n",
    "                selected_attributes = options[1:]\n",
    "\n",
    "            fields = selected_attributes\n",
    "            if view_choice.value == 'All Profiles':\n",
    "                response = table.scan(ProjectionExpression=', '.join(fields))\n",
    "                for item in response['Items']:\n",
    "                    display = ', '.join([f\"{key}: {value}\" for key, value in item.items()])\n",
    "                    print(display)\n",
    "            elif view_choice.value == \"Search Profile by Username\" and username.value:\n",
    "                response = table.query(\n",
    "                    KeyConditionExpression=Key('username').eq(username.value),\n",
    "                    ProjectionExpression=', '.join(fields)\n",
    "                )\n",
    "                for item in response['Items']:\n",
    "                    display = ', '.join([f\"{key}: {value}\" for key, value in item.items()])\n",
    "                    print(display)\n",
    "                if not response['Items']:\n",
    "                    print(\"Username does not exist, Please Enter another one\")\n",
    "            else:\n",
    "                print(\"Invalid Choice or No username Entered\")\n",
    "\n",
    "    search_button.on_click(valid_search)\n",
    "\n",
    "    # Function to clear the output\n",
    "    def clear(click):\n",
    "        with output:\n",
    "            clear_output()\n",
    "\n",
    "    clear_button.on_click(clear)\n",
    "\n",
    "    # Function to handle visibility of username input\n",
    "    def username_visibility(change):\n",
    "        if change['new'] == 'Search Profile by Username':\n",
    "            labeled_username.layout.visibility = 'visible'\n",
    "            username.layout.visibility = 'visible'\n",
    "        else:\n",
    "            labeled_username.layout.visibility = 'hidden'\n",
    "            username.layout.visibility = 'hidden'\n",
    "            username.value = ''\n",
    "\n",
    "    view_choice.observe(username_visibility, names='value')\n",
    "\n",
    "    # Display the GUI\n",
    "    buttons = widgets.HBox([search_button, clear_button])\n",
    "    layout = widgets.VBox([labeled_view_choice, labeled_username, labeled_attributes, buttons, output])\n",
    "    display(layout)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "ff2bdf57",
   "metadata": {},
   "outputs": [],
   "source": [
    "def change_mongo():\n",
    "    \n",
    "    # to have labels in HTMl so it fits on the screen\n",
    "    def labeled_input(description, widget):\n",
    "        return widgets.VBox([widgets.Label(value=f\"{description}\"), widget])\n",
    "\n",
    "    # widgets that will appear on the main menu to give user the option to select \"Insert\", \"Delete\",\n",
    "    # or \"Modify\"\n",
    "    action = widgets.Dropdown(options = [\"Insert\", \"Delete\", \"Modify\"])\n",
    "    labeled_action = labeled_input(\"Action: \", action)\n",
    "    \n",
    "    submit = widgets.Button(description = \"Submit\")\n",
    "    \n",
    "    clear_button = widgets.Button(\n",
    "        description = 'Clear', \n",
    "        button_style = '', \n",
    "        tooltip = 'Click to clear search', \n",
    "        icon = 'remove')\n",
    "    \n",
    "    output = widgets.Output()\n",
    "\n",
    "    # function so that based on which option is selected, the correct action will occur\n",
    "    def choice(click):\n",
    "        with output:\n",
    "            clear_output()\n",
    "            if action.value == \"Insert\":\n",
    "                valid_insert()\n",
    "            elif action.value == \"Delete\":\n",
    "                valid_delete()\n",
    "            elif action.value == \"Modify\":\n",
    "                valid_modify()\n",
    "\n",
    "    # valid_insert is function for if the user selects insert\n",
    "    def valid_insert():\n",
    "\n",
    "        # widgets that will be used if user selects \"Insert\", have a form widget and message widget\n",
    "        form_output = widgets.Output()\n",
    "        message_output = widgets.Output()\n",
    "        \n",
    "        username = widgets.Text()\n",
    "        email = widgets.Text()\n",
    "        wins = widgets.IntText(min = 0)\n",
    "        losses = widgets.IntText(min = 0)\n",
    "        kills = widgets.IntText(min = 0)\n",
    "        number_of_friends = widgets.IntText(min = 0)\n",
    "        favorite_weapon = widgets.Text()\n",
    "        money_spent = widgets.FloatText(min = 0.0)\n",
    "        favorite_character = widgets.Text()\n",
    "\n",
    "        # function so that user can insert a new profile, user is able to enter all 10 fields to make the\n",
    "        # new profile; function ensures that username and email cannot be left blank or a duplicate entry and that\n",
    "        # numerical values have to be greater than or equal to 0, wins, losses, number of friends and kills must be ints,\n",
    "        # money spent can be a float\n",
    "        def insert(submission):\n",
    "            with message_output:\n",
    "                message_output.clear_output()\n",
    "                if not username.value.strip() or not email.value.strip():\n",
    "                    print(\"Username and email cannot be left blank.\")\n",
    "                    return\n",
    "                #profile_inserted = True\n",
    "                try: \n",
    "                    if any(int(value) < 0 for value in [wins.value, losses.value, kills.value, number_of_friends.value]):\n",
    "                        print(\"Wins, losses, kills and number of friends must be an integer greater than or equal to 0.\")\n",
    "                        return\n",
    "                        \n",
    "                    if float(money_spent.value) < 0 :\n",
    "                        print(\"Money spent must be a number greater than or equal to 0.\")\n",
    "                        return\n",
    "                except ValueError:\n",
    "                    print(\"Non numeric value entered for wins, losses, kills, number of friends, or money spent\")\n",
    "                    \n",
    "                if collection.find_one({\"username\": username.value}) or collection.find_one({\"email\": email.value}): \n",
    "                    print(\"Username or Email already in use. Please enter a new one.\")\n",
    "                    return\n",
    "                profile_data = {\n",
    "                    \"username\": username.value,\n",
    "                    \"email\": email.value,\n",
    "                    \"wins\": wins.value,\n",
    "                    \"losses\": losses.value,\n",
    "                    \"games_played\": wins.value+losses.value,\n",
    "                    \"kills\": kills.value,\n",
    "                    \"number_of_friends\": number_of_friends.value,\n",
    "                    \"favorite_weapon\": favorite_weapon.value,\n",
    "                    \"money_spent\": money_spent.value,\n",
    "                    \"favorite_character\": favorite_character.value,\n",
    "                  \n",
    "                }\n",
    "                collection.insert_one(profile_data)\n",
    "                print(\"Profile Inserted\")\n",
    "                \n",
    "        insert_button = widgets.Button(description = \"Insert\")\n",
    "        insert_button.on_click(insert)\n",
    "\n",
    "        \n",
    "        # widgets that will be displayed when insert is selected\n",
    "        insert_items = [labeled_input('Username: ', username), \n",
    "                  labeled_input('Email: ', email), \n",
    "                  labeled_input('Wins: ', wins),\n",
    "                  labeled_input('Losses: ', losses), \n",
    "                  labeled_input('Kills: ', kills), \n",
    "                  labeled_input('Number of Friends: ', number_of_friends), \n",
    "                  labeled_input('Favorite Weapon: ', favorite_weapon), \n",
    "                  labeled_input('Money Spent: ', money_spent),\n",
    "                  labeled_input('Favorite Character: ', favorite_character),\n",
    "                  insert_button]\n",
    "        \n",
    "        display(form_output)\n",
    "        for item in insert_items:\n",
    "            display(item)\n",
    "        display(message_output)\n",
    "\n",
    "    # valid_delete is function for if the user selects delete\n",
    "    def valid_delete():\n",
    "\n",
    "        # widgets that will be used if user selects delete\n",
    "        output = widgets.Output()   \n",
    "        output.clear_output(wait = True)\n",
    "        numeric_conditions_container = widgets.VBox([])\n",
    "        favorite_conditions_container = widgets.VBox([])\n",
    "        \n",
    "        delete_button = widgets.Button(description =  \"Delete\")\n",
    "\n",
    "        username = widgets.Text()\n",
    "        labeled_username = labeled_input(\"Username: \", username)\n",
    "\n",
    "        options = ['all', 'wins', 'losses', 'games_played', 'kills', 'number_of_friends',\n",
    "                       'money_spent', 'favorite_character']\n",
    "        fields_to_delete = widgets.SelectMultiple(\n",
    "            options = options,\n",
    "            value = ['all'],\n",
    "            disabled = False\n",
    "        )\n",
    "        labeled_fields_to_delete = labeled_input('Field(s) to Delete: ', fields_to_delete)\n",
    "        \n",
    "        \n",
    "        number_of_numeric_conditions = widgets.Dropdown(\n",
    "            options = [0,1,2,3,4,5,6],\n",
    "            value = 0,\n",
    "            disabled = False,\n",
    "        )\n",
    "        labeled_number_of_numeric_conditions = labeled_input(\"Number of Numeric Conditions: \", number_of_numeric_conditions)\n",
    "\n",
    "        \n",
    "        number_of_favorite_conditions = widgets.Dropdown(\n",
    "            options = [0,1,2],\n",
    "            value = 0,\n",
    "            disabled = False,\n",
    "        )\n",
    "        labeled_number_of_favorite_conditions = labeled_input(\"Number of Favorite Conditions: \", number_of_favorite_conditions)\n",
    "\n",
    "        operator = widgets.Dropdown(\n",
    "            options = ['Select', 'AND', 'OR'],\n",
    "            value = \"Select\",\n",
    "            disabled = False\n",
    "        )\n",
    "        labeled_operator = labeled_input(\"Operator: \", operator)\n",
    "       \n",
    "        # this function allows user to select how many numeric conditions they would like; numeric fields include\n",
    "        # 'wins', 'losses', 'games played', 'kills', 'number of friends', and 'money spent'; function will \n",
    "        # display number of numeric condition widgets according to the number selected by user. \n",
    "        def num_of_numeric_conditions(change):\n",
    "            children = []\n",
    "            for i in range(change['new']):\n",
    "                field_choice = widgets.Dropdown(\n",
    "                    options = ['select', 'wins', 'losses', 'games_played', 'kills', \n",
    "                               'number_of_friends', 'money_spent'],\n",
    "                    disabled = False\n",
    "                )\n",
    "                labeled_field_choice = labeled_input(\"Field Choice: \", field_choice)\n",
    "                \n",
    "                operator_choice = widgets.Dropdown(\n",
    "                    options = ['select', '=', '>', '>=', '<', '<='],\n",
    "                    disabled = False\n",
    "                )\n",
    "                labeled_operator_choice = labeled_input(\"Operator Choice: \", operator_choice)\n",
    "                \n",
    "                value = widgets.FloatText(\n",
    "                value = 0,\n",
    "                disabled = False\n",
    "                )\n",
    "                labeled_value = labeled_input(\"Value: \", value)\n",
    "                \n",
    "                condition_row = widgets.HBox([labeled_field_choice, labeled_operator_choice, labeled_value])\n",
    "                children.append(condition_row)\n",
    "            numeric_conditions_container.children = children\n",
    "\n",
    "        number_of_numeric_conditions.observe(num_of_numeric_conditions, names = 'value')\n",
    "    \n",
    " \n",
    "        # this function allows user to select how many favorite conditions they would like; favorite fields include\n",
    "        # favorite character and favorite weapon; function will \n",
    "        # display number of favorite condition widgets according to the number selected by user\n",
    "        def num_of_favorite_conditions(change):\n",
    "            children = []\n",
    "            for i in range(change['new']):\n",
    "                field = widgets.Dropdown(\n",
    "                    options = ['select', 'favorite_character', 'favorite_weapon'],\n",
    "                    disabled = False\n",
    "                )\n",
    "                labeled_field = labeled_input(\"Field Choice: \", field)\n",
    "                \n",
    "                operation = widgets.Dropdown(\n",
    "                    options = ['select', '=', '≠'],\n",
    "                    disabled = False\n",
    "                )\n",
    "                labeled_operation = labeled_input(\"Operation Choice: \", operation)\n",
    "                \n",
    "                favorite = widgets.Text(\n",
    "                    disabled = False\n",
    "                )\n",
    "                labeled_favorite = labeled_input(\"Value: \", favorite)\n",
    "                \n",
    "                condition_row = widgets.HBox([labeled_field, labeled_operation, labeled_favorite])\n",
    "                children.append(condition_row)\n",
    "            favorite_conditions_container.children = children\n",
    "\n",
    "        number_of_favorite_conditions.observe(num_of_favorite_conditions, names = 'value')\n",
    "\n",
    " \n",
    "        # delete function will delete the profile(s) or column(s) in database; deletion is based on either\n",
    "        # the username entered by the user or based on the numeric and/or the favorite conditions; numeric\n",
    "        # conditions give user the option to select the numeric fields described above, as well as one of the conditions,\n",
    "        # <, >, <=, >=, =, and the value to compare and delete based on the conditions; favorite conditions\n",
    "        # give the user the option to select the favorite fields as described above, as well as one of the conditions,\n",
    "        # = or ≠ and the value to compare to and delete based on the conditions; user can select multiple conditions\n",
    "        # from either favorite or numeric and select AND or OR to join them; function also gives user the option to\n",
    "        # select how many fields to delete, or all to delete an entire profile; finally, function will tell user \n",
    "        # how many profile(s) or column(s) were deleted\n",
    "        def delete(submission):\n",
    "            with output:\n",
    "                clear_output()\n",
    "                query_conditions = []\n",
    "\n",
    "                if username.value:\n",
    "                    query_conditions.append({\"username\": username.value})\n",
    "\n",
    "                for search_condition in numeric_conditions_container.children + favorite_conditions_container.children:\n",
    "                    field, condition, value = [c.children[1].value for c in search_condition.children]\n",
    "                    if field != 'select' and condition != 'select':\n",
    "                        query_conditions.append(numeric_query(field, condition, value))\n",
    "\n",
    "                logical_operator = {\"AND\": \"$and\", \"OR\": \"$or\"}.get(operator.value, \"$and\")\n",
    "\n",
    "                query = {logical_operator:query_conditions} if query_conditions else{}\n",
    "                \n",
    "                \n",
    "                if 'all' in fields_to_delete.value:\n",
    "                    result = collection.delete_one({logical_operator: query_conditions})\n",
    "                    print(f\"Deleted {result.deleted_count} profiles\")\n",
    "                else:\n",
    "                    if not query_conditions:\n",
    "                        print(\"Specify username or condition to delete.\")\n",
    "                        return\n",
    "                    fields_to_unset = {field: \"\" for field in fields_to_delete.value if field != 'all'}\n",
    "\n",
    "                    if fields_to_unset:\n",
    "                        result = collection.update_many(query, {\"$unset\": fields_to_unset})\n",
    "                    if result.modified_count > 0:\n",
    "                        print(f\"Field(s) {', '.join(fields_to_unset)} deleted from {result.modified_count} profile(s).\")\n",
    "                    else:\n",
    "                        print(\"No fields were deleted\")\n",
    "            \n",
    "        # function so that user can not select 'all' with other options for field(s) to delete to avoid\n",
    "        # redundancy; user can either select other fields together or all by itself.\n",
    "        def select_all(change):\n",
    "            if 'all' in change['new']:\n",
    "                if len(change['new']) > 1:\n",
    "                    if 'all' in change['old']:\n",
    "                        fields_to_delete.value = tuple(set(change['new']) - {'all'})\n",
    "                    else:\n",
    "                        fields_to_delete.value = tuple(options[1:])\n",
    "                else:\n",
    "                    fields_to_delete.value = ('all',)\n",
    "            \n",
    "        fields_to_delete.observe(select_all, 'value')\n",
    "\n",
    " \n",
    "        # widgets that will be displayed when delete is selected\n",
    "        delete_button.on_click(delete)\n",
    "        show_widgets = [\n",
    "            labeled_fields_to_delete,\n",
    "            labeled_username,\n",
    "            labeled_number_of_numeric_conditions,\n",
    "            numeric_conditions_container,\n",
    "            labeled_number_of_favorite_conditions,\n",
    "            favorite_conditions_container,\n",
    "            labeled_operator,\n",
    "            delete_button,\n",
    "            output\n",
    "        ]\n",
    "        display(*show_widgets)\n",
    "\n",
    "    \n",
    "    # valid_modify is function for if the user selects modify\n",
    "    def valid_modify():\n",
    "\n",
    "        # widgets that will be used if user selects modify\n",
    "        output = widgets.Output()\n",
    "        numeric_conditions_container = widgets.VBox([])\n",
    "        favorite_conditions_container = widgets.VBox([])\n",
    "        modify_button = widgets.Button(description = \"Modify\")\n",
    "        \n",
    "        username = widgets.Text()\n",
    "        labeled_username = labeled_input(\"Username: \", username)\n",
    "\n",
    "        options = ['username', 'email', 'wins', 'losses', 'kills', 'number_of_friends',\n",
    "                       'money_spent', 'favorite_character', 'favorite_weapon']\n",
    "        fields_to_modify = widgets.SelectMultiple(\n",
    "            options = options,\n",
    "            disabled = False\n",
    "        )\n",
    "        labeled_fields_to_modify = labeled_input('Column(s) to Modify: ', fields_to_modify)\n",
    "\n",
    "        number_of_numeric_conditions = widgets.Dropdown(\n",
    "            options = [0,1,2,3,4,5,6],\n",
    "            value = 0,\n",
    "            disabled = False,\n",
    "        )\n",
    "        labeled_number_of_numeric_conditions = labeled_input(\"Number of Numeric Conditions: \", number_of_numeric_conditions)\n",
    "\n",
    "        \n",
    "        number_of_favorite_conditions = widgets.Dropdown(\n",
    "            options = [0,1,2],\n",
    "            value = 0,\n",
    "            disabled = False,\n",
    "        )\n",
    "        labeled_number_of_favorite_conditions = labeled_input(\"Number of Favorite Conditions: \", number_of_favorite_conditions)\n",
    "\n",
    "        operator = widgets.Dropdown(\n",
    "            options = ['Select', 'AND', 'OR'],\n",
    "            value = \"Select\",\n",
    "            disabled = False\n",
    "        )\n",
    "        labeled_operator = labeled_input(\"Operator: \", operator)\n",
    "\n",
    "        modify_fields_container = widgets.VBox([])\n",
    "\n",
    "        # function so that user can select which field(s) they want to change and a textbox will\n",
    "        # appear where they can input the new value for the corresponding field(s) they want to change\n",
    "        def fields_modify(change):\n",
    "            children = []\n",
    "            for field in change['new']:\n",
    "                value_input = widgets.Text()\n",
    "                labeled_value_input = labeled_input(f\"New {field}: \", value_input)\n",
    "                children.append(labeled_value_input)\n",
    "            modify_fields_container.children = children\n",
    "\n",
    "        fields_to_modify.observe(fields_modify, names = 'value')\n",
    "\n",
    "        # this function(like the one for delete) allows user to select how many numeric conditions they would like; numeric fields include\n",
    "        # 'wins', 'losses', 'games played', 'kills', 'number of friends', and 'money spent'; function will \n",
    "        # display number of numeric condition widgets according to the number selected by user. \n",
    "        def num_of_numeric_conditions(change):\n",
    "            children = []\n",
    "            for i in range(change['new']):\n",
    "                field_choice = widgets.Dropdown(\n",
    "                    options = ['select', 'wins', 'games_played', 'losses', 'kills', \n",
    "                               'number_of_friends', 'money_spent'],\n",
    "                    disabled = False\n",
    "                )\n",
    "                labeled_field_choice = labeled_input(\"Field Choice: \", field_choice)\n",
    "                \n",
    "                operator_choice = widgets.Dropdown(\n",
    "                    options = ['select', '=', '>', '>=', '<', '<='],\n",
    "                    disabled = False\n",
    "                )\n",
    "                labeled_operator_choice = labeled_input(\"Operator Choice: \", operator_choice)\n",
    "                \n",
    "                value = widgets.FloatText(\n",
    "                value = 0,\n",
    "                disabled = False\n",
    "                )\n",
    "                labeled_value = labeled_input(\"Value: \", value)\n",
    "                \n",
    "                condition_row = widgets.HBox([labeled_field_choice, labeled_operator_choice, labeled_value])\n",
    "                children.append(condition_row)\n",
    "            numeric_conditions_container.children = children\n",
    "\n",
    "        number_of_numeric_conditions.observe(num_of_numeric_conditions, names = 'value')\n",
    "\n",
    "        # this function(like the one for delete) allows user to select how many favorite conditions they would like; favorite fields include\n",
    "        # favorite character and favorite weapon; function will display number of favorite condition \n",
    "        # widgets according to the number selected by user\n",
    "        def num_of_favorite_conditions(change):\n",
    "            children = []\n",
    "            for i in range(change['new']):\n",
    "                field = widgets.Dropdown(\n",
    "                    options = ['select', 'favorite_character', 'favorite_weapon'],\n",
    "                    disabled = False\n",
    "                )\n",
    "                labeled_field = labeled_input(\"Field Choice: \", field)\n",
    "                \n",
    "                operation = widgets.Dropdown(\n",
    "                    options = ['select', '=', '≠'],\n",
    "                    disabled = False\n",
    "                )\n",
    "                labeled_operation = labeled_input(\"Operation Choice: \", operation)\n",
    "                \n",
    "                favorite = widgets.Text(\n",
    "                    disabled = False\n",
    "                )\n",
    "                labeled_favorite = labeled_input(\"Value: \", favorite)\n",
    "                \n",
    "                condition_row = widgets.HBox([labeled_field, labeled_operation, labeled_favorite])\n",
    "                children.append(condition_row)\n",
    "            favorite_conditions_container.children = children\n",
    "\n",
    "        number_of_favorite_conditions.observe(num_of_favorite_conditions, names = 'value')\n",
    "\n",
    "\n",
    "        # modify function will modify the profile(s) or column(s) in database; modification is based on either\n",
    "        # the username entered by the user or based on the numeric and/or the favorite conditions; numeric\n",
    "        # conditions give user the option to select the numeric fields described above, as well as one of the conditions,\n",
    "        # <, >, <=, >=, =, and the value to compare and modify based on the conditions; favorite conditions\n",
    "        # give the user the option to select the favorite fields as described above, as well as one of the conditions,\n",
    "        # = or ≠ and the value to compare to and modify based on the conditions; user can select multiple conditions\n",
    "        # from either favorite or numeric and select AND or OR to join them; user will also be given option\n",
    "        # to select which fields they want to modify and input the new values.\n",
    "        # finally, function will tell user how many profile(s)/column(s) were modified\n",
    "        def modify(submission):\n",
    "            with output:\n",
    "                clear_output()\n",
    "                query_conditions = []\n",
    "\n",
    "                if username.value:\n",
    "                    query_conditions.append({\"username\": username.value})\n",
    "\n",
    "                for search_condition in numeric_conditions_container.children + favorite_conditions_container.children:\n",
    "                    field, condition, value = [c.children[1].value for c in search_condition.children]\n",
    "                    if field != 'select' and condition != 'select':\n",
    "                        query_conditions.append(numeric_query(field, condition, value))\n",
    "\n",
    "                logical_operator = {\"AND\": \"$and\", \"OR\": \"$or\"}.get(operator.value, \"$and\")\n",
    "\n",
    "                query = {logical_operator:query_conditions} if query_conditions else{}\n",
    "            \n",
    "                if not query_conditions:\n",
    "                    print(\"Specify username or condition to delete.\")\n",
    "                    return\n",
    "\n",
    "                modify_values = {}\n",
    "\n",
    "                for i in modify_fields_container.children:\n",
    "                    label_widget = i.children[0]\n",
    "                    text_widget = i.children[1]\n",
    "                    \n",
    "                    field = label_widget.value.replace(\"New\", \"\").replace(\":\", \"\").strip().lower()\n",
    "                    original_value = text_widget.value.strip()\n",
    "                    modify_values[field] = original_value if original_value else None\n",
    "\n",
    "                    if field in ['username', 'email'] and not original_value:\n",
    "                        print(f\"Cannot leave '{field}' blank\")\n",
    "                        return\n",
    "                        \n",
    "                    if field in ['wins', 'losses',  'kills', 'number_of_friends']:\n",
    "                        try:\n",
    "                            value = int(original_value)\n",
    "                            if value < 0:\n",
    "                                print(f\"New Value for {field} cannot be negative.\")\n",
    "                                return\n",
    "\n",
    "                        except ValueError:\n",
    "                            print(f\"New Value for {field} must be a integer greater than or equal to 0.\")\n",
    "                            return\n",
    "                    elif field in ['money_spent']:\n",
    "                        try:\n",
    "                            value = int(original_value)\n",
    "                            if value < 0:\n",
    "                                print(\"New Value for 'money_spent' cannot be negative.\")\n",
    "                                return\n",
    "\n",
    "                        except ValueError:\n",
    "                            print(print(\"New Value for 'money_spent' must be a number greater than or equal to 0.\"))\n",
    "                            return\n",
    "                    else:\n",
    "                        value = original_value\n",
    "                            \n",
    "                    modify_values[field.strip()] = value\n",
    "\n",
    "                if 'wins' in modify_values or 'losses' in modify_values:\n",
    "                    current_profile = collection.find_one({\"username\": username.value})\n",
    "                    if current_profile:\n",
    "                        current_wins = modify_values.get('wins', current_profile.get('wins', 0))\n",
    "                        current_losses = modify_values.get('losses', current_profile.get('losses', 0))\n",
    "                        modify_values['games_played'] = current_wins+current_losses\n",
    "                        \n",
    "\n",
    "                \n",
    "                if modify_values:\n",
    "                    result = collection.update_many(query, {\"$set\": modify_values})\n",
    "                    if result.modified_count > 0:\n",
    "                        print(f\"Modified {result.modified_count} profile(s)\")\n",
    "                    else:\n",
    "                        print(\"No profiles were modified\")\n",
    "                         \n",
    "        modify_button.on_click(modify)\n",
    "\n",
    "        # widgets that will be displayed when modify is selected\n",
    "        show_widgets = [\n",
    "            labeled_fields_to_modify,\n",
    "            labeled_username,\n",
    "            labeled_number_of_numeric_conditions,\n",
    "            numeric_conditions_container,\n",
    "            labeled_number_of_favorite_conditions,\n",
    "            favorite_conditions_container,\n",
    "            labeled_operator,\n",
    "            modify_fields_container,\n",
    "            modify_button,\n",
    "            output\n",
    "        ]\n",
    "        display(*show_widgets)\n",
    "    \n",
    "    # used to translate the symbols to the Mongo syntax\n",
    "    def numeric_query(field, condition, value):\n",
    "        operators = {\n",
    "            \">\":\"$gt\",\n",
    "            \"<\":\"$lt\",\n",
    "            \">=\":\"$gte\",\n",
    "            \"<=\":\"$lte\",\n",
    "            \"=\":\"$eq\",\n",
    "            \"≠\":\"$ne\"\n",
    "        }\n",
    "        return {field: {operators[condition]: value}}\n",
    "        \n",
    "        num_of_condition({'new': 1})\n",
    "\n",
    "    # delete and modify button\n",
    "    #delete_button = widgets.Button(description = \"Delete\")\n",
    "    #modify_button = widgets.Button(description = \"Modify\")\n",
    "    \n",
    "   \n",
    "    # to clear when clicked on \n",
    "    def clear(click):\n",
    "        with output:\n",
    "            clear_output()\n",
    "       \n",
    "    submit.on_click(choice)\n",
    "    clear_button.on_click(clear)\n",
    "\n",
    "    # display for the main menu\n",
    "    buttons = widgets.HBox([submit, clear_button])\n",
    "    display(labeled_action, buttons, output)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "78155b8f-8e1d-4f8e-8d68-d4dd9bbf2549",
   "metadata": {},
   "outputs": [],
   "source": [
    "def change_dynamo():\n",
    "\n",
    "    def labeled_input(description, widget):\n",
    "        return widgets.VBox([widgets.Label(value=f\"{description}\"), widget])\n",
    "\n",
    "    action = widgets.Dropdown(options=[\"Insert\", \"Delete\", \"Modify\"])\n",
    "    labeled_action = labeled_input(\"Action: \", action)\n",
    "\n",
    "    submit = widgets.Button(description=\"Submit\")\n",
    "    clear_button = widgets.Button(description='Clear', button_style='', tooltip='Click to clear search', icon='remove')\n",
    "    output = widgets.Output()\n",
    "\n",
    "    def choice(click):\n",
    "        with output:\n",
    "            clear_output()\n",
    "            if action.value == \"Insert\":\n",
    "                valid_insert()\n",
    "            elif action.value == \"Delete\":\n",
    "                valid_delete()\n",
    "            elif action.value == \"Modify\":\n",
    "                valid_modify()\n",
    "\n",
    "    def valid_insert():\n",
    "        form_output = widgets.Output()\n",
    "        message_output = widgets.Output()\n",
    "\n",
    "        username = widgets.Text()\n",
    "        email = widgets.Text()\n",
    "        wins = widgets.IntText(min=0)\n",
    "        losses = widgets.IntText(min=0)\n",
    "        kills = widgets.IntText(min=0)\n",
    "        number_of_friends = widgets.IntText(min=0)\n",
    "        favorite_weapon = widgets.Text()\n",
    "        money_spent = widgets.FloatText(min=0.0)\n",
    "        favorite_character = widgets.Text()\n",
    "\n",
    "        def insert(submission):\n",
    "            with message_output:\n",
    "                message_output.clear_output()\n",
    "                if not username.value.strip() or not email.value.strip():\n",
    "                    print(\"Username and email cannot be left blank.\")\n",
    "                    return\n",
    "    \n",
    "                try:\n",
    "                    if any(int(value) < 0 for value in [wins.value, losses.value, kills.value, number_of_friends.value]):\n",
    "                        print(\"Wins, losses, kills, and number of friends must be integers greater than or equal to 0.\")\n",
    "                        return\n",
    "    \n",
    "                    if money_spent.value < 0:\n",
    "                        print(\"Money spent must be a number greater than or equal to 0.\")\n",
    "                        return\n",
    "                except ValueError:\n",
    "                    print(\"Non-numeric value entered for wins, losses, kills, number of friends, or money spent.\")\n",
    "                    return\n",
    "    \n",
    "                # checks if username already exists\n",
    "                # variable key is the one getting queried\n",
    "                username_response = table.query(\n",
    "                    KeyConditionExpression=Key('username').eq(username.value)\n",
    "                )\n",
    "                if username_response['Items']:\n",
    "                    print(\"Username already in use. Please enter a new one.\")\n",
    "                    return\n",
    "    \n",
    "                # Scan the table to check if email already exists\n",
    "                email_exists = False\n",
    "                response = table.scan(\n",
    "                    FilterExpression=Attr('email').eq(email.value)\n",
    "                )\n",
    "                for item in response['Items']:\n",
    "                    if item['email'] == email.value:\n",
    "                        email_exists = True\n",
    "                        break\n",
    "    \n",
    "                if email_exists:\n",
    "                    print(\"Email already in use. Please enter a new one.\")\n",
    "                    return\n",
    "    \n",
    "                # Insert the new profile into DynamoDB\n",
    "                profile_data = {\n",
    "                    \"username\": username.value,\n",
    "                    \"email\": email.value,\n",
    "                    \"wins\": wins.value,\n",
    "                    \"losses\": losses.value,\n",
    "                    \"games_played\": wins.value + losses.value,\n",
    "                    \"kills\": kills.value,\n",
    "                    \"number_of_friends\": number_of_friends.value,\n",
    "                    \"favorite_weapon\": favorite_weapon.value,\n",
    "                    \"money_spent\": Decimal(str(money_spent.value)),\n",
    "                    \"favorite_character\": favorite_character.value,\n",
    "                }\n",
    "                table.put_item(Item=profile_data)\n",
    "                print(\"Profile Inserted\")\n",
    "    \n",
    "        insert_button = widgets.Button(description=\"Insert\")\n",
    "        insert_button.on_click(insert)\n",
    "    \n",
    "        insert_items = [\n",
    "            labeled_input('Username: ', username),\n",
    "            labeled_input('Email: ', email),\n",
    "            labeled_input('Wins: ', wins),\n",
    "            labeled_input('Losses: ', losses),\n",
    "            labeled_input('Kills: ', kills),\n",
    "            labeled_input('Number of Friends: ', number_of_friends),\n",
    "            labeled_input('Favorite Weapon: ', favorite_weapon),\n",
    "            labeled_input('Money Spent: ', money_spent),\n",
    "            labeled_input('Favorite Character: ', favorite_character),\n",
    "            insert_button\n",
    "        ]\n",
    "    \n",
    "        display(form_output)\n",
    "        for item in insert_items:\n",
    "            display(item)\n",
    "        display(message_output)\n",
    "    \n",
    "\n",
    "    def valid_delete():\n",
    "        output = widgets.Output()\n",
    "        output.clear_output(wait=True)\n",
    "    \n",
    "        username = widgets.Text()\n",
    "        labeled_username = labeled_input(\"Username: \", username)\n",
    "    \n",
    "        delete_button = widgets.Button(description=\"Delete\")\n",
    "    \n",
    "        def delete(submission):\n",
    "            with output:\n",
    "                output.clear_output()\n",
    "                # Check if username exists\n",
    "                response = table.query(\n",
    "                    KeyConditionExpression=Key('username').eq(username.value))\n",
    "        \n",
    "                if not response['Items']:\n",
    "                    print(\"No profile found with the given username.\")\n",
    "                    return\n",
    "        \n",
    "                # Delete the profile(s) from DynamoDB\n",
    "                for item in response['Items']:\n",
    "                    # Use both username and email as key elements to delete the item\n",
    "                    table.delete_item(\n",
    "                        Key={'username': item['username'], 'email': item['email']}\n",
    "                    )\n",
    "                print(\"Profile(s) Deleted\")\n",
    "\n",
    "        delete_button.on_click(delete)\n",
    "    \n",
    "        show_widgets = [\n",
    "            labeled_username,\n",
    "            delete_button,\n",
    "            output\n",
    "        ]\n",
    "        display(*show_widgets)\n",
    "\n",
    "\n",
    "    # valid_modify is function for if the user selects modify\n",
    "    def valid_modify():\n",
    "    \n",
    "        # widgets that will be used if user selects modify\n",
    "        output = widgets.Output()\n",
    "        numeric_conditions_container = widgets.VBox([])\n",
    "        favorite_conditions_container = widgets.VBox([])\n",
    "        modify_button = widgets.Button(description=\"Modify\")\n",
    "    \n",
    "        username = widgets.Text()\n",
    "        email = widgets.Text()\n",
    "        labeled_username = labeled_input(\"Username: \", username)\n",
    "        labeled_email = labeled_input(\"Email: \", email)\n",
    "    \n",
    "        options = ['username', 'email', 'wins', 'losses', 'kills', 'number_of_friends',\n",
    "                   'money_spent', 'favorite_character', 'favorite_weapon']\n",
    "        fields_to_modify = widgets.SelectMultiple(\n",
    "            options=options,\n",
    "            disabled=False\n",
    "        )\n",
    "        labeled_fields_to_modify = labeled_input('Column(s) to Modify: ', fields_to_modify)\n",
    "    \n",
    "        modify_fields_container = widgets.VBox([])\n",
    "    \n",
    "        # function so that user can select which field(s) they want to change and a textbox will\n",
    "        # appear where they can input the new value for the corresponding field(s) they want to change\n",
    "        def fields_modify(change):\n",
    "            children = []\n",
    "            for field in change['new']:\n",
    "                value_input = widgets.Text()\n",
    "                labeled_value_input = labeled_input(f\"New {field}: \", value_input)\n",
    "                children.append(labeled_value_input)\n",
    "            modify_fields_container.children = children\n",
    "    \n",
    "        fields_to_modify.observe(fields_modify, names='value')\n",
    "\n",
    "    \n",
    "        # modify function will modify the profile(s) or column(s) in database; modification is based on \n",
    "        # the username entered by the user. user will also be given option\n",
    "        # to select which fields they want to modify and input the new values.\n",
    "            \n",
    "        def modify(submission):\n",
    "            with output:\n",
    "                clear_output()\n",
    "                query_conditions = []\n",
    "\n",
    "                # key = {'username': username.value, 'email': email.value}\n",
    "                key = {'username': username.value, 'email': email.value}\n",
    "                \n",
    "                # Check if the key is valid\n",
    "                if not key: \n",
    "                    print(\"Key is missing.\")\n",
    "                    return\n",
    "                if not username.value:\n",
    "                    print(\"Please provide a valid username.\")\n",
    "                    return\n",
    "        \n",
    "                # Add username condition if provided\n",
    "                if username.value:\n",
    "                    query_conditions.append({\"username\": username.value})\n",
    "                            \n",
    "                \n",
    "                # Construct FilterExpression based on query conditions\n",
    "                query = {\"FilterExpression\": \" AND \".join([f\"({condition})\" for condition in query_conditions])} if query_conditions else {}\n",
    "        \n",
    "                if not query_conditions:\n",
    "                    print(\"Specify username or condition to delete.\")\n",
    "                    return\n",
    "                \n",
    "                modify_values = {}\n",
    "                \n",
    "                # Iterate through fields to modify and their new values\n",
    "                for i in modify_fields_container.children:\n",
    "                    label_widget = i.children[0]\n",
    "                    text_widget = i.children[1]\n",
    "                            \n",
    "                    field = label_widget.value.replace(\"New\", \"\").replace(\":\", \"\").strip().lower()\n",
    "                    original_value = text_widget.value.strip()\n",
    "                \n",
    "                    if field in ['username', 'email'] and not original_value:\n",
    "                        print(f\"Cannot leave '{field}' blank\")\n",
    "                        return\n",
    "                                \n",
    "                    if field in ['wins', 'losses',  'kills', 'number_of_friends']:\n",
    "                        try:\n",
    "                            value = int(original_value)\n",
    "                            if value < 0:\n",
    "                                print(f\"New Value for {field} cannot be negative.\")\n",
    "                                return\n",
    "                \n",
    "                        except ValueError:\n",
    "                            print(f\"New Value for {field} must be a integer greater than or equal to 0.\")\n",
    "                            return\n",
    "                    elif field in ['money_spent']:\n",
    "                        try:\n",
    "                            value = int(original_value)\n",
    "                            if value < 0:\n",
    "                                print(\"New Value for 'money_spent' cannot be negative.\")\n",
    "                                return\n",
    "                \n",
    "                        except ValueError:\n",
    "                            print(print(\"New Value for 'money_spent' must be a number greater than or equal to 0.\"))\n",
    "                            return\n",
    "                    else:\n",
    "                        value = original_value\n",
    "                                    \n",
    "                    modify_values[field.strip()] = value\n",
    "\n",
    "                \n",
    "                # Calculate games played based on wins and losses if they are modified\n",
    "                if 'wins' in modify_values or 'losses' in modify_values:\n",
    "                    response = table.query(KeyConditionExpression=Key('username').eq(username.value))\n",
    "                    items = response['Items']\n",
    "                    if items:\n",
    "                        current_profile = items[0]  # Assuming there's only one item matching the key\n",
    "                    else:\n",
    "                        current_profile = {}\n",
    "                    # current_profile = response.get('Item', {})\n",
    "                                \n",
    "                    current_wins = int(modify_values.get('wins', str(current_profile.get('wins', {'N': '0'}))))\n",
    "                    current_losses = int(modify_values.get('losses', str(current_profile.get('losses', {'N': '0'}))))\n",
    "\n",
    "                    games_played = current_wins + current_losses\n",
    "                    modify_values['games_played'] = {'N': str(games_played)}\n",
    "        \n",
    "                if modify_values:\n",
    "                    update_expression = \"SET \" + \", \".join([f\"#{k.strip()} = :{k.strip()}\" for k in modify_values.keys()])\n",
    "                    expression_attribute_values = {f\":{k.strip()}\": v for k, v in modify_values.items()}\n",
    "                    expression_attribute_names = {\"#{}\".format(k.strip()): k.strip() for k in modify_values.keys()}\n",
    "                \n",
    "                    # print(\"Update Expression:\", update_expression)\n",
    "                    # print(\"Expression Attribute Values:\", expression_attribute_values)\n",
    "                    # print(\"Expression Attribute Names:\", expression_attribute_names)\n",
    "                \n",
    "                    try:\n",
    "                        # Attempt to update the item in the database\n",
    "                        response = table.update_item(\n",
    "                            Key=key,\n",
    "                            UpdateExpression=update_expression,\n",
    "                            ExpressionAttributeValues=expression_attribute_values,\n",
    "                            ExpressionAttributeNames=expression_attribute_names,\n",
    "                            ReturnValues=\"UPDATED_NEW\"\n",
    "                        )\n",
    "                        if 'Attributes' in response:\n",
    "                            print(\"Modified profile(s)\".format(response['Attributes']))\n",
    "                        else:\n",
    "                            print(\"No profiles were modified\")\n",
    "                    except Exception as e:\n",
    "                        print(\"Failed to update item:\", e)\n",
    "\n",
    "\n",
    "    # Attach the callback function to the \"Modify\" button\n",
    "    # modify_button.on_click(modify_button_clicked)\n",
    "    \n",
    "        modify_button.on_click(modify)\n",
    "    \n",
    "        # widgets that will be displayed when modify is selected\n",
    "        show_widgets = [\n",
    "            labeled_fields_to_modify,\n",
    "            labeled_username,\n",
    "            labeled_email,\n",
    "            modify_fields_container,\n",
    "            modify_button,\n",
    "            output\n",
    "        ]\n",
    "        display(*show_widgets)\n",
    "    \n",
    "    \n",
    "    # used to translate the symbols to the DynamoDB syntax\n",
    "    def numeric_query(field, condition, value):\n",
    "        operators = {\n",
    "            \">\": \"gt\",\n",
    "            \"<\": \"lt\",\n",
    "            \">=\": \"gte\",\n",
    "            \"<=\": \"lte\",\n",
    "            \"=\": \"eq\",\n",
    "            \"≠\": \"ne\"\n",
    "        }\n",
    "        return Attr(field).contains({operators[condition]: Decimal(str(value))})\n",
    "\n",
    "    def clear(click):\n",
    "        with output:\n",
    "            clear_output()\n",
    "    \n",
    "    submit.on_click(choice)\n",
    "    clear_button.on_click(clear)\n",
    "\n",
    "    buttons = widgets.HBox([submit, clear_button])\n",
    "    display(labeled_action, buttons, output)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "88f6072f",
   "metadata": {},
   "outputs": [],
   "source": [
    "def search_mongo():\n",
    "\n",
    "    # to have labels in HTMl so it fits on the screen, make it bold too\n",
    "    def labeled_input(description, widget):\n",
    "        return widgets.VBox([widgets.Label(value=f\"{description}\"), widget])\n",
    "\n",
    "    # widgets that will be used for this function\n",
    "    options = [ 'all', 'username', 'email', 'games_played', 'wins', 'losses',\n",
    "                  'kills', 'number_of_friends', 'favorite_weapon', 'money_spent', \n",
    "                  'favorite_character']\n",
    "    attributes = widgets.SelectMultiple(\n",
    "        options = options,\n",
    "        value = ['all'],\n",
    "        disabled = False\n",
    "    )\n",
    "    labeled_attributes = labeled_input(\"Attributes(hold command to select multiple): \", attributes)\n",
    "\n",
    "    operator = widgets.Dropdown(\n",
    "        options = ['Select', 'AND', 'OR'],\n",
    "        value = 'Select',\n",
    "        disabled = False\n",
    "    )\n",
    "    labeled_operator = labeled_input(\"Operator: \", operator)\n",
    "\n",
    "\n",
    "    number_of_numerical_conditions = widgets.Dropdown(\n",
    "        options = [0,1,2,3,4,5,6],\n",
    "        value = 0,\n",
    "        disabled = False,\n",
    "    )\n",
    "    labeled_number_of_numerical_conditions = labeled_input(\"Number of Numeric Conditions: \", number_of_numerical_conditions)\n",
    "\n",
    "\n",
    "    number_of_favorite_conditions = widgets.Dropdown(\n",
    "        options = [0,1,2],\n",
    "        value = 0,\n",
    "        disabled = False,\n",
    "    )\n",
    "    labeled_number_of_favorite_conditions = labeled_input(\"Number of Favorite Conditions: \", number_of_favorite_conditions)\n",
    "\n",
    "    \n",
    "    search_container_numerical = widgets.VBox([])\n",
    "    search_container_favorite= widgets.VBox([])\n",
    "    \n",
    "    search_button = widgets.Button(\n",
    "        description = 'Search',\n",
    "        button_style = '',\n",
    "        tooltip = \"Click to Search\",\n",
    "        icon = 'search'\n",
    "    )\n",
    "    clear_button = widgets.Button(\n",
    "        description = 'Clear', \n",
    "        button_style = '', \n",
    "        tooltip = 'Click to clear search', \n",
    "        icon = 'remove')\n",
    "    output = widgets.Output()\n",
    "\n",
    "    # function so user can't select all along with the other options, only all, or only the other options\n",
    "    def select_all(change):\n",
    "        if 'all' in change['new']:\n",
    "            if len(change['new']) > 1:\n",
    "                if 'all' in change['old']:\n",
    "                    attributes.value = tuple(set(change['new']) - {'all'})\n",
    "                else:\n",
    "                    attributes.value = tuple(options[1:])\n",
    "            else:\n",
    "                attributes.value = ('all',)\n",
    "    \n",
    "    attributes.observe(select_all, 'value')\n",
    "    \n",
    "    # this function allows user to select how many numeric conditions they would like; numeric fields include\n",
    "    # 'wins', 'losses', 'games played', 'kills', 'number of friends', and 'money spent'; function will \n",
    "    # display number of numeric condition widgets according to the number selected by user; unlike previous\n",
    "    # num_of_numerical_conditions, user will also have the option to search for max or min values; \n",
    "    # when that occurs, the value widget will disappear\n",
    "    def num_of_numerical_conditions(change):\n",
    "        conditions = change['new'] \n",
    "        children = []\n",
    "        for _ in range(conditions):\n",
    "            field = widgets.Dropdown(\n",
    "                options = ['select', 'wins', 'losses', 'games_played', 'kills', 'number_of_friends', 'money_spent'],\n",
    "                disabled = False\n",
    "            )\n",
    "            condition = widgets.Dropdown(\n",
    "                options = ['select', '=', '>', '>=', '<', '<=', 'max', 'min'],\n",
    "                disabled = False\n",
    "            )\n",
    "            value = widgets.FloatText(\n",
    "                value = 0,\n",
    "                disabled = False\n",
    "            )\n",
    "            value_container = widgets.VBox(children = [widgets.HTML(value = \"<b>Value:</b>\"), value])\n",
    "\n",
    "            def value_visibile(change, container = value_container):\n",
    "                if change['new'] in ['max', 'min']:\n",
    "                    container.layout.display = 'none'\n",
    "                else:\n",
    "                    container.layout.display = ''\n",
    "\n",
    "            condition.observe(value_visibile, names = 'value')\n",
    "\n",
    "            \n",
    "            children.append(widgets.HBox([labeled_input('Field: ', field), labeled_input('Condition: ', condition), value_container]))\n",
    "        search_container_numerical.children = children\n",
    "    \n",
    "    num_of_numerical_conditions({'new': number_of_numerical_conditions.value})\n",
    "    number_of_numerical_conditions.observe(num_of_numerical_conditions, names = 'value')\n",
    "\n",
    "    # this function allows user to select how many favorite conditions they would like; favorite fields include\n",
    "    # 'favorite character' and 'favorite weapon'; function will \n",
    "    # display number of favorite condition widgets according to the number selected by user \n",
    "    # unlike previous num_of_favorite_conditions, user will also have the option to search for most \n",
    "    # or least common values; when that occurs, the value widget will disappear\n",
    "    def num_of_favorite_conditions(change):\n",
    "        conditions = change['new'] \n",
    "        children = []\n",
    "        for _ in range(conditions):\n",
    "            field = widgets.Dropdown(\n",
    "                options = ['select', 'favorite_character', 'favorite_weapon'],\n",
    "                disabled = False\n",
    "            )\n",
    "            condition = widgets.Dropdown(\n",
    "                options = ['select', '=','≠'],\n",
    "                disabled = False\n",
    "            )\n",
    "            value = widgets.Text(\n",
    "                disabled = False\n",
    "            )\n",
    "            value_container = widgets.VBox(children = [widgets.HTML(value = \"<b>Value:</b>\"), value])\n",
    "            \n",
    "            children.append(widgets.HBox([labeled_input('Field: ', field), labeled_input('Condition: ', condition), value_container]))\n",
    "        search_container_favorite.children = children\n",
    "\n",
    "    num_of_favorite_conditions({'new': number_of_favorite_conditions.value})\n",
    "    number_of_favorite_conditions.observe(num_of_favorite_conditions, names = 'value')\n",
    "\n",
    "    # this function will will search for profiles based on the numeric and/or the favorite conditions; numeric\n",
    "    # conditions give user the option to select the numeric fields described above, as well as one of the conditions,\n",
    "    # <, >, <=, >=, =, max or min and the value(except for max and min) to compare and return profiles based on the conditions; \n",
    "    # favorite conditions give the user the option to select the favorite fields as described above, as well as one of the conditions,\n",
    "    # =, ≠, most common or least common and the value to compare to(except for most/least common) to compare and return profiles based on the conditions; \n",
    "    # user can select multiple conditions from either favorite or numeric and select AND or OR to join them; user will also be given option\n",
    "    # to select which fields they want to see or select all to see all the fields\n",
    "    # finally, function will tell user how many profile(s)/field(s) were founding matching the conditions\n",
    "    def search_button_clicked(search):\n",
    "        with output:\n",
    "            clear_output()\n",
    "            selected_attributes = list(attributes.value)\n",
    "            if 'all' in selected_attributes:\n",
    "                selected_attributes = options[1:]\n",
    "            fields = {field: 1 for field in selected_attributes}\n",
    "            fields['_id'] = 0\n",
    "            \n",
    "            query_conditions = []\n",
    "            logical_operator = \"$and\"\n",
    "            if operator.value in ['AND', 'OR']:\n",
    "                logical_operator = \"$and\" if operator.value == 'AND' else \"$or\"\n",
    "\n",
    "            \n",
    "            max_min = []\n",
    "            if number_of_numerical_conditions.value > 0:\n",
    "                for search_condition in search_container_numerical.children:\n",
    "                    field_widget, condition_widget, value_widget = search_condition.children\n",
    "                    field = field_widget.children[1].value\n",
    "                    condition = condition_widget.children[1].value\n",
    "                    value =  value_widget.children[1].value\n",
    "                    if field == 'select' or condition == 'select':\n",
    "                        print(\"No field or condition selected, please select one.\")\n",
    "                        return\n",
    "                    elif field != 'select' and condition in ['max', 'min']:\n",
    "                        max_min.append((field,condition))\n",
    "                    else:\n",
    "                        subquery = numeric_query(field, condition, value)\n",
    "                        query_conditions.append(subquery)\n",
    "\n",
    "            favorite_max_min = []\n",
    "            if number_of_favorite_conditions.value > 0:\n",
    "                for search_condition in search_container_favorite.children:\n",
    "                    field_widget,condition_widget,value_widget = search_condition.children\n",
    "                    field = field_widget.children[1].value\n",
    "                    condition = condition_widget.children[1].value\n",
    "                    value = value_widget.children[1].value\n",
    "                    \n",
    "                    if field == 'select' or condition == 'select':\n",
    "                        print(\"No field or condition selected, please select one.\")\n",
    "                        return\n",
    "  \n",
    "                    elif field != 'select' and condition != 'select':\n",
    "                        subquery = numeric_query(field, condition, value)\n",
    "                        query_conditions.append(subquery)\n",
    " \n",
    "                    else:\n",
    "                        subquery = numeric_query(field, condition, value)\n",
    "                        query_conditions.append(subquery)\n",
    "\n",
    "\n",
    "            for field, condition in max_min:\n",
    "                sort_order = -1 if condition == 'max' else 1\n",
    "                pipe = [\n",
    "                    {\"$match\": {field: {\"$exists\": True, \"$ne\": None}}},\n",
    "                    {\"$sort\": {field: sort_order}},\n",
    "                    {\"$limit\": 1}\n",
    "                ]\n",
    "                result = list(collection.aggregate(pipe))\n",
    "                if result and field in result[0]:\n",
    "                    max_or_min = result[0][field]\n",
    "                    match = {\"$eq\": max_or_min}\n",
    "                    query_conditions.append({field: max_or_min})\n",
    "                else:\n",
    "                    print(\"No value found\")\n",
    "                \n",
    "                        \n",
    "            if query_conditions:\n",
    "                query = {logical_operator: query_conditions} if len(query_conditions) > 1 else(query_conditions[0] if query_conditions\n",
    "                                                                                              else {})\n",
    "                profiles = collection.find(query, fields)\n",
    "                count = collection.count_documents(query)\n",
    "                if count == 0:\n",
    "                    print(\"No profiles found matching you search\")\n",
    "                else:\n",
    "                    print(f\"{count} profile(s) found matching your search\")\n",
    "                    for profile in profiles:\n",
    "                        out = ', '.join([f\"{key}: {value}\" for key, value in profile.items() if key != '_id'])\n",
    "                        print(out)\n",
    "    search_button.on_click(search_button_clicked)\n",
    "\n",
    "    # display the widgets for this function\n",
    "    buttons = widgets.HBox([search_button, clear_button])\n",
    "    display(labeled_operator, labeled_number_of_numerical_conditions, search_container_numerical, \n",
    "            labeled_number_of_favorite_conditions,  search_container_favorite, labeled_attributes,\n",
    "            buttons, output)\n",
    "\n",
    "    # clear to reset the values and clear the output\n",
    "    def clear(click):\n",
    "        with output:\n",
    "            clear_output()\n",
    "        number_of_numerical_conditions.value = 0\n",
    "        num_of_numerical_conditions({'new': 0})\n",
    "        number_of_favorite_conditions.value = 0\n",
    "        num_of_favorite_conditions({'new': 0})\n",
    "\n",
    "\n",
    "    clear_button.on_click(clear)\n",
    "\n",
    "     # used to translate the symbols to the Mongo syntax like above\n",
    "    def numeric_query(field, condition, value):\n",
    "        operators = {\n",
    "            \">\":\"$gt\",\n",
    "            \"<\":\"$lt\",\n",
    "            \">=\":\"$gte\",\n",
    "            \"<=\":\"$lte\",\n",
    "            \"=\":\"$eq\",\n",
    "            \"≠\":\"$ne\"\n",
    "        }\n",
    "        return {field: {operators[condition]: value}}\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "988ec6a9-56d5-43cd-adb1-11ff65ee2a0a",
   "metadata": {},
   "outputs": [],
   "source": [
    "def search_dynamo():\n",
    "\n",
    "    # Function to create labeled input widgets\n",
    "    def labeled_input(description, widget):\n",
    "        return widgets.VBox([widgets.Label(value=f\"{description}\"), widget])\n",
    "\n",
    "    # Widgets setup\n",
    "    options = ['all', 'username', 'email', 'games_played', 'wins', 'losses',\n",
    "               'kills', 'number_of_friends', 'favorite_weapon', 'money_spent',\n",
    "               'favorite_character']\n",
    "    attributes = widgets.SelectMultiple(\n",
    "        options=options,\n",
    "        value=['all'],\n",
    "        disabled=False\n",
    "    )\n",
    "    labeled_attributes = labeled_input(\"Attributes (hold command to select multiple): \", attributes)\n",
    "\n",
    "    operator = widgets.Dropdown(\n",
    "        options=['Select', 'AND', 'OR'],\n",
    "        value='Select',\n",
    "        disabled=False\n",
    "    )\n",
    "    labeled_operator = labeled_input(\"Operator: \", operator)\n",
    "\n",
    "    number_of_numerical_conditions = widgets.Dropdown(\n",
    "        options=[0, 1, 2, 3, 4, 5, 6],\n",
    "        value=0,\n",
    "        disabled=False,\n",
    "    )\n",
    "    labeled_number_of_numerical_conditions = labeled_input(\"Number of Numeric Conditions: \",\n",
    "                                                           number_of_numerical_conditions)\n",
    "\n",
    "    number_of_favorite_conditions = widgets.Dropdown(\n",
    "        options=[0, 1, 2],\n",
    "        value=0,\n",
    "        disabled=False,\n",
    "    )\n",
    "    labeled_number_of_favorite_conditions = labeled_input(\"Number of Favorite Conditions: \",\n",
    "                                                           number_of_favorite_conditions)\n",
    "\n",
    "    search_container_numerical = widgets.VBox([])\n",
    "    search_container_favorite = widgets.VBox([])\n",
    "\n",
    "    search_button = widgets.Button(\n",
    "        description='Search',\n",
    "        button_style='',\n",
    "        tooltip=\"Click to Search\",\n",
    "        icon='search'\n",
    "    )\n",
    "    clear_button = widgets.Button(\n",
    "        description='Clear',\n",
    "        button_style='',\n",
    "        tooltip='Click to clear search',\n",
    "        icon='remove')\n",
    "    output = widgets.Output()\n",
    "\n",
    "    def select_all(change):\n",
    "        if 'all' in change['new']:\n",
    "            if len(change['new']) > 1:\n",
    "                if 'all' in change['old']:\n",
    "                    attributes.value = tuple(set(change['new']) - {'all'})\n",
    "                else:\n",
    "                    attributes.value = tuple(options[1:])\n",
    "            else:\n",
    "                attributes.value = ('all',)\n",
    "\n",
    "    attributes.observe(select_all, 'value')\n",
    "\n",
    "    def num_of_numerical_conditions(change):\n",
    "        conditions = change['new']\n",
    "        children = []\n",
    "        for _ in range(conditions):\n",
    "            field = widgets.Dropdown(\n",
    "                options=['select', 'wins', 'losses', 'games_played', 'kills', 'number_of_friends', 'money_spent'],\n",
    "                disabled=False\n",
    "            )\n",
    "            condition = widgets.Dropdown(\n",
    "                options=['select', '=', '>', '>=', '<', '<=', '≠'],\n",
    "                disabled=False\n",
    "            )\n",
    "            value = widgets.FloatText(\n",
    "                value=0,\n",
    "                disabled=False\n",
    "            )\n",
    "            value_container = widgets.VBox(children=[widgets.HTML(value=\"<b>Value:</b>\"), value])\n",
    "\n",
    "            def value_visible(change, container=value_container):\n",
    "                if change['new'] in ['max', 'min']:\n",
    "                    container.layout.display = 'none'\n",
    "                else:\n",
    "                    container.layout.display = ''\n",
    "\n",
    "            condition.observe(value_visible, names='value')\n",
    "\n",
    "            children.append(widgets.HBox([labeled_input('Field: ', field), labeled_input('Condition: ', condition),\n",
    "                                          value_container]))\n",
    "        search_container_numerical.children = children\n",
    "\n",
    "    num_of_numerical_conditions({'new': number_of_numerical_conditions.value})\n",
    "    number_of_numerical_conditions.observe(num_of_numerical_conditions, names='value')\n",
    "\n",
    "    def num_of_favorite_conditions(change):\n",
    "        conditions = change['new']\n",
    "        children = []\n",
    "        for _ in range(conditions):\n",
    "            field = widgets.Dropdown(\n",
    "                options=['select', 'favorite_character', 'favorite_weapon'],\n",
    "                disabled=False\n",
    "            )\n",
    "            condition = widgets.Dropdown(\n",
    "                options=['select', '=', '≠'],\n",
    "                disabled=False\n",
    "            )\n",
    "            value = widgets.Text(\n",
    "                disabled=False\n",
    "            )\n",
    "            value_container = widgets.VBox(children=[widgets.HTML(value=\"<b>Value:</b>\"), value])\n",
    "\n",
    "            children.append(widgets.HBox([labeled_input('Field: ', field), labeled_input('Condition: ', condition),\n",
    "                                          value_container]))\n",
    "        search_container_favorite.children = children\n",
    "\n",
    "    num_of_favorite_conditions({'new': number_of_favorite_conditions.value})\n",
    "    number_of_favorite_conditions.observe(num_of_favorite_conditions, names='value')\n",
    "\n",
    "    def search_button_clicked(search):\n",
    "        with output:\n",
    "            output.clear_output()\n",
    "            selected_attributes = list(attributes.value)\n",
    "            if 'all' in selected_attributes:\n",
    "                selected_attributes = options[1:]\n",
    "            projection_expression = ', '.join(selected_attributes)\n",
    "\n",
    "            logical_operator = \"AND\"\n",
    "            if operator.value in ['AND', 'OR']:\n",
    "                logical_operator = \"AND\" if operator.value == 'AND' else \"OR\"\n",
    "\n",
    "            query_conditions = []\n",
    "\n",
    "            if number_of_numerical_conditions.value > 0:\n",
    "                for search_condition in search_container_numerical.children:\n",
    "                    field_widget, condition_widget, value_widget = search_condition.children\n",
    "                    field = field_widget.children[1].value\n",
    "                    condition = condition_widget.children[1].value\n",
    "                    value = value_widget.children[1].value\n",
    "\n",
    "                    if field != 'select' and condition != 'select':\n",
    "                        query_conditions.append(numeric_query(field, condition, value))\n",
    "\n",
    "            if number_of_favorite_conditions.value > 0:\n",
    "                for search_condition in search_container_favorite.children:\n",
    "                    field_widget, condition_widget, value_widget = search_condition.children\n",
    "                    field = field_widget.children[1].value\n",
    "                    condition = condition_widget.children[1].value\n",
    "                    value = value_widget.children[1].value\n",
    "\n",
    "                    if field != 'select' and condition != 'select':\n",
    "                        query_conditions.append(favorite_query(field, condition, value))\n",
    "\n",
    "            if query_conditions:\n",
    "                if logical_operator == \"AND\":\n",
    "                    filters = reduce(lambda x, y: x & y, query_conditions)\n",
    "                else:\n",
    "                    filters = reduce(lambda x, y: x | y, query_conditions)\n",
    "\n",
    "                response = table.scan(\n",
    "                    ProjectionExpression=projection_expression,\n",
    "                    FilterExpression=filters\n",
    "                )\n",
    "\n",
    "                items = response['Items']\n",
    "                print(f\"{len(items)} item(s) found matching your search.\")\n",
    "                for item in items:\n",
    "                    print(item)\n",
    "\n",
    "    search_button.on_click(search_button_clicked)\n",
    "\n",
    "    buttons = widgets.HBox([search_button, clear_button])\n",
    "    display(labeled_operator, labeled_number_of_numerical_conditions, search_container_numerical,\n",
    "            labeled_number_of_favorite_conditions, search_container_favorite, labeled_attributes,\n",
    "            buttons, output)\n",
    "\n",
    "    def clear(click):\n",
    "        with output:\n",
    "            output.clear_output()\n",
    "        number_of_numerical_conditions.value = 0\n",
    "        num_of_numerical_conditions({'new': 0})\n",
    "        number_of_favorite_conditions.value = 0\n",
    "        num_of_favorite_conditions({'new': 0})\n",
    "\n",
    "    clear_button.on_click(clear)\n",
    "\n",
    "\n",
    "def numeric_query(field, condition, value):\n",
    "    operators = {\n",
    "        \">\": \"gt\",\n",
    "        \"<\": \"lt\",\n",
    "        \">=\": \"gte\",\n",
    "        \"<=\": \"lte\",\n",
    "        \"=\": \"eq\",\n",
    "        \"≠\": \"ne\"\n",
    "    }\n",
    "\n",
    "    value = Decimal(str(value))\n",
    "    \n",
    "    return getattr(Key(field), operators[condition])(value)\n",
    "\n",
    "\n",
    "def favorite_query(field, condition, value):\n",
    "    if condition == \"=\":\n",
    "        return Attr(field).eq(value)\n",
    "    elif condition == \"≠\":\n",
    "        return Attr(field).ne(value)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "576e2905-71ee-44e2-b7e8-33a7cc70d03a",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "7ee227105c194b68aba4039d75195bb4",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "VBox(children=(Label(value='Select Database'), Dropdown(options=('MongoDB', 'DynamoDB'), value='MongoDB')))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "6d0e9a80df9c43eba659d60b56b3526f",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "VBox(children=(Label(value='Select Operation'), Dropdown(options=('View', 'Change', 'Search'), value='View')))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "794789af7a2b41c4946ae55703f1974b",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Button(description='Search', style=ButtonStyle(), tooltip='Click to clear search')"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "b4091688e04a4a96a2259c679ee766ff",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Output()"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "def selection():\n",
    "    # to have labels in HTMl so it fits on the screen\n",
    "    def labeled_input(description, widget):\n",
    "        return widgets.VBox([widgets.Label(value=f\"{description}\"), widget])\n",
    "\n",
    "    # widgets that will be used, including dropdown to select database and select operation\n",
    "    database_selection = widgets.Dropdown(\n",
    "        options = ['MongoDB', 'DynamoDB'],\n",
    "        value = 'MongoDB',\n",
    "        disabled = False\n",
    "    )\n",
    "    database_selection_labeled = labeled_input(\"Select Database\", database_selection)\n",
    "\n",
    "    operation_selection= widgets.Dropdown(\n",
    "        options = ['View', 'Change', 'Search'],\n",
    "        value = 'View',\n",
    "        disabled = False\n",
    "    )\n",
    "    operation_selection_labeled = labeled_input(\"Select Operation\", operation_selection)\n",
    "    \n",
    "    operation_button = widgets.Button(\n",
    "        description = 'Search', \n",
    "        button_style = '', \n",
    "        tooltip = 'Click to clear search', \n",
    "    )\n",
    "    output = widgets.Output()\n",
    "\n",
    "    # function that executes the proper function based on the database the user selects and the operation the user selects\n",
    "    def operation_execution(operation):\n",
    "        with output:\n",
    "            output.clear_output()\n",
    "            if database_selection.value == 'MongoDB':\n",
    "                if operation_selection.value == 'View':\n",
    "                    view_mongo()\n",
    "                elif operation_selection.value == 'Change':\n",
    "                    change_mongo()\n",
    "                elif operation_selection.value == 'Search':\n",
    "                    search_mongo()\n",
    "            elif database_selection.value == 'DynamoDB':\n",
    "                if operation_selection.value == 'View':\n",
    "                    view_dynamo()\n",
    "                elif operation_selection.value == 'Change':\n",
    "                    change_dynamo()\n",
    "                elif operation_selection.value == 'Search':\n",
    "                    search_dynamo()\n",
    "\n",
    "    # display buttons and ensure when the operation button is clicked, the function executse\n",
    "    operation_button.on_click(operation_execution)\n",
    "    display(database_selection_labeled, operation_selection_labeled, operation_button, output)\n",
    "\n",
    "selection()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fdf4b706-c29f-40c7-99c3-e26e08a2c8a9",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
